### ISSUE TITLE
Possible to create circle - whatever the image size is?

### ISSUE THREAD

**Issue by Rainer-Lang** [vinc3m1/RoundedImageView#100]
eg I have images in different sizes - sometimes width is greater than height and sometimes vice versa.
But I want always a circle, not an oval.

**Comment by vinc3m1** [comment]
As long as the ImageView has height and width constrained, it should be a circle regardless of what bitmap you pass in. Then use ScaleType as needed for fit/crop.

**Comment by Rainer-Lang** [comment]
I make square images - then all is fine.
