### ISSUE TITLE
Custom Drawable in setImageDrawable = invalid canvas size

### ISSUE THREAD

**Issue by sosite** [vinc3m1/RoundedImageView#102]
I try to used custom DummyDrawable on ImageView and RoundedImageView via `imageView.setImageDrawable(new DummyDrawable())`.

```java
public class DummyDrawable extends Drawable {
    @Override
    public void draw(Canvas canvas) {
        Path path = new Path();
        path.moveTo(canvas.getWidth() / 2, 0);
        path.lineTo(0, canvas.getHeight() / 2);
        path.lineTo(canvas.getWidth() / 2, canvas.getHeight());
        path.lineTo(canvas.getWidth(), canvas.getHeight() / 2);
        path.lineTo(canvas.getWidth() / 2, 0);

        Paint paint = new Paint();
        paint.setColor(Color.BLUE);

        canvas.drawPath(path, paint);
    }

    ...
}
```

The results is hmm... interesting. On standard ImageView (on the left) everythings works like a charm. But on RoundedImageView (on the right) i get invalid `canvas.getWidth()` and `canvas.getHeight()` results - `int 2` in place of `int 100`.

![roundedimageview](https://cloud.githubusercontent.com/assets/2025949/7670935/e857c05e-fcb8-11e4-9098-cfdb82b8efd8.png)

The interesting thing is that when I add `DummyDrawable` as background `imageView.setBackgroundDrawable(new DummyDrawable())` everything work like a charm.

**Comment by vinc3m1** [comment]
Custom drawables aren't supported. If you're going to make a custom drawable you might as well implement the rounding yourself as it's not that complicated, and would be much more performant.

If you wanted to you could probably get by with passing back proper values in getIntrinsicHeight/Width but it would also be very inefficient because RIV would render your drawable to a bitmap then scale it as needed.

**Comment by sosite** [comment]
The problem is that I need custom drawable only as a placeholder when loading image from internet.

**Comment by vinc3m1** [comment]
You can use RoundedDrawable directly on a regular ImageView, swap in RoundedDrawable when you're done loading.
