### ISSUE TITLE
Selector doesn't when add as ImageDrawable

### ISSUE THREAD

**Issue by sosite** [vinc3m1/RoundedImageView#103]
Other problem with image drawables is not working selectors when add via `setImageDrawable(getResources.getDrawable(R.drawable.working_selector))` while
`setBackgroundDrawable(...)` works fine.

Drawable haven't called `changeState(final int[] stateSet)` and probably it's a problem.

**Comment by vinc3m1** [comment]
RIV doesn't officially support complex state drawables, it does best effort, but no guarantees.
