### ISSUE TITLE
Attributes and Setters not equally named -> New Android Databinding fails

### ISSUE THREAD

**Issue by kashban** [vinc3m1/RoundedImageView#107]
I am implementing Android Databinding with RoundedImageView and since the Class does not have the Setters and Getters named as the XML attributes, the automatic binding fails. 

https://developer.android.com/tools/data-binding/guide.html#renamed_setters

Unfortunately Android Binding is currently unable to support custom control attributes for setter renaming, so that Binding is not available for RoundedImageView. 

I also tried extending the View to something else and create setters accordingly, but that won't work either. 

So I suggest either renaming the setters and getters like the xml attributes or adding setters/getters accordingly (like setRivOval(boolean oval)).

Will try some other things too, though.

**Comment by vinc3m1** [comment]
Not familiar with databinding, do custom setters work? https://developer.android.com/tools/data-binding/guide.html#custom_setters

**Comment by kashban** [comment]
Yes, it works. My problem had a different origin, namely either a bug in the Databinding library or its documentation. 

I filed a bug report at Google :

https://code.google.com/p/android/issues/detail?id=177407&q=Databinding&colspec=ID%20Type%20Status%20Owner%20Summary%20Stars
