### ISSUE TITLE
Add usage for Android Databinding to Readme.MD

### ISSUE THREAD

**Issue by kashban** [vinc3m1/RoundedImageView#108]
Vince, I got RoundedImageView working with the new Android Databinding support library (https://developer.android.com/tools/data-binding/guide.html).

How about adding this to the Usage section of Readme.MD? I'm willing to fork and create a Pull Request for this, if you're interested.

Context: I have a WYSIWYG representation of RIV in my App Picture Calendar (https://play.google.com/store/apps/details?id=de.kashban.android.picturecalendar) which can be changed on the fly by switches and sliders. Currently this is done on the settings tab under Picture Frame Design without databinding. I am now implementing WYSIWYG for the whole Calendar Design and started using Databinding. The first control bound happens to be RIV. 

Cheers
Jürgen

Screenshots of WYSIWYG-Calendar Designer Work in Progress:

![riv_databinding1](https://cloud.githubusercontent.com/assets/6595407/8248548/b1c11178-1660-11e5-9b03-bf7da7014e33.png)
![riv_databinding2](https://cloud.githubusercontent.com/assets/6595407/8248551/b54f976a-1660-11e5-94cb-68a63c786563.png)

**Comment by vinc3m1** [comment]
Please PR with a short and sweet usage section if you're interested. Or a sample fragment would be good too.

**Comment by kashban** [comment]
I created a pull request with a verbose example fragment. It also shows how to get user input and reflect that on RIV by databinding.
