### ISSUE TITLE
Inefficient usage of non-bitmap drawable

### ISSUE THREAD

**Issue by Yarikx** [vinc3m1/RoundedImageView#112]
There is one performance issue while using this view.
As this view is aimed to be used with bitmaps and BitmapDrawable for maximum efficiency, it convert any non-bitmap drawable to BitmapDrawable to wrap it with RoundedDrawable.
This is super efficient with bitmaps, but create additional allocation of bitmap for other drawables.

When using this view in adapter and showing bitmap and not-bitmap drawables it creates measurable amount of allocations. As particular case you can imagine using Picasso to load bitmaps while using GradientDrawable as placeholder.

It would be good to implement 'fallback' mode, when user set non-bitmap drawable draw it with 'clipPath' or other options to draw rounded drawbles without creating additional bitmaps

**Comment by vinc3m1** [comment]
For Picasso you should use [`RoundedTransformation`](https://github.com/vinc3m1/RoundedImageView/blob/master/roundedimageview/src/main/java/com/makeramen/roundedimageview/RoundedTransformationBuilder.java) so it only rounds the downloaded bitmap, then supply your own pre-rounded placeholder with gradient.
