### ISSUE TITLE
not work when makeSceneTransitionAnimation

### ISSUE THREAD

**Issue by echo-lgtm** [vinc3m1/RoundedImageView#113]
makeSceneTransitionAnimation  not work

**Comment by vinc3m1** [comment]
Please provide more information or I have no idea what the problem actually is and will close this ticket.

**Comment by Arjun-sna** [comment]
@vinc3m1 when used with shared element transition using makeScenTransitionAnimation() method,  the image view transition animation is working fine but there is problem with scaling to new dimensions.

**Comment by vlahakis** [comment]
I am getting this too. Would be nice to allow transitions. Any progress?

**Comment by fxedel** [comment]
Same here, but sometimes only when `oval` is true.

#### `.setOval(false)`
![screenshot_20160623-181455](https://cloud.githubusercontent.com/assets/7782229/16311194/d944a74a-396f-11e6-9b80-26b0c1f58bcf.png) Bitmap (Vertical screenshot)
![screenshot_20160623-181500](https://cloud.githubusercontent.com/assets/7782229/16311187/d3008444-396f-11e6-9c25-656890c2e8eb.png) Bitmap (Horizontal photo)
![screenshot_20160623-181518](https://cloud.githubusercontent.com/assets/7782229/16311201/e0943bf0-396f-11e6-941e-4b2856bbff54.png) Vector Drawable

#### `.setOval(true)`
![screenshot_20160623-181615](https://cloud.githubusercontent.com/assets/7782229/16311223/f9bf722a-396f-11e6-80b5-82f8f7371416.png)
![screenshot_20160623-181619](https://cloud.githubusercontent.com/assets/7782229/16311224/f9c47144-396f-11e6-8fec-f32ef1a4c18e.png)
![screenshot_20160623-181518](https://cloud.githubusercontent.com/assets/7782229/16311201/e0943bf0-396f-11e6-941e-4b2856bbff54.png)

As you can see, the Vector Drawable (maybe all drawables?) is cut also without using `oval` – no idea what causes this issue.

The bitmaps aren't square, they're centered and cropped using `scaleType="centerCrop"`. Without using shared elements, the oval is among the visible image border. But with shared elements, it seems to be using the left and top visible border and the right and bottom invisible (out of content area) border.
