### ISSUE TITLE
`RoundedImageView#setBorderColor(int)` color parameter should be annotated with `@ColorInt` instead of `@ColorRes`

### ISSUE THREAD

**Issue by desseim** [vinc3m1/RoundedImageView#114]
The parameter is passed as is to `ColorStateList#valueOf(int)` which takes a colors value and not a color resource, and local tests confirm that the color is only correctly applied when passed as a color value.

Lint issues an error though when calling `RoundedImageView#setBorderColor(int)` with a color value which is highly misleading.

Simply annotate the parameter with `@ColorInt` instead.

Reference: https://sites.google.com/a/android.com/tools/tech-docs/support-annotations

**Comment by vinc3m1** [comment]
Good catch.. will get this fixed
