### ISSUE TITLE
RoundedImageView appearing with black border since 2.1.0

### ISSUE THREAD

**Issue by dlew** [vinc3m1/RoundedImageView#115]
Since updating to 2.1.0+, we've noticed black borders being drawn on `RoundedImageView`:

![](http://i.imgur.com/9Kpkp5p.png)

We're recycling the `RoundedImageView`; the differences are either calling `setOval()` with true/false, and loading different images w/ Picasso.

Going back to 2.0.1 fixes the problem:

![](http://i.imgur.com/g4GRpjr.png)

Since we don't need the capabilities of 2.1.0+, we've just reverted to 2.0.1 as a solution. As a result I haven't dug too deeply into what's going on.

**Comment by vinc3m1** [comment]
Huh, very interesting... will look into it

**Comment by vinc3m1** [comment]
Can't seem to reproduce this, mind digging deeper when you get a chance? Also if you're using Picasso are you using the [TransformationBuilder](https://github.com/vinc3m1/RoundedImageView/blob/master/roundedimageview/src/main/java/com/makeramen/roundedimageview/RoundedTransformationBuilder.java)?

**Comment by dlew** [comment]
I'll see if I can find time this week to dig into it.

I'm not using `TransformationBuilder`, but I'm also not using `Transformations` so that shouldn't be the issue.

**Comment by dlew** [comment]
I haven't dug into *why* it's happening but it's incredibly easy to reproduce. I was able to do it with a single simple `Activity` using this layout:

```xml
<FrameLayout xmlns:android="http://schemas.android.com/apk/res/android"
             android:layout_width="match_parent"
             android:layout_height="match_parent"
             android:background="@android:color/white"
  >

  <com.makeramen.roundedimageview.RoundedImageView
    android:layout_width="wrap_content"
    android:layout_height="wrap_content"
    android:layout_gravity="center"
    android:src="@drawable/ic_launcher"
    />

</FrameLayout>
```

If you want I can upload the whole project but that's basically all of it.

**Comment by vinc3m1** [comment]
No need for a project, seems simple enough. Thanks! Also just in case, what
API are you targeting and running on?

**Comment by dlew** [comment]
Targeting 22, running on 4.4.4 and 5.1.1.

**Comment by paetztm** [comment]
Looks like on line 307 of RoundedDrawable you need:

    if (mBorderWidth > 0) {
        canvas.drawRect(mBorderRect, mBorderPaint);
    }

Not sure if that's the only place but that fixes the issue for me.
