### ISSUE TITLE
how to display image from net when i use Universal-Image-Loader or bitmapUtils?

### ISSUE THREAD

**Issue by hdjtdxwt** [vinc3m1/RoundedImageView#117]
it show a blank image ,how to fix

**Comment by liboLiao** [comment]
I used the same effect as setImageBitmap(...)

**Comment by bacy** [comment]
bitmapUtils convert drawable to AsyncDrawable, but here it convert to RoundDrawable,which cause a conflict

**Comment by vinc3m1** [comment]
closing due to issue age
