### ISSUE TITLE
Image is not loaded after crossfade animation from Glide in Recyclerview

### ISSUE THREAD

**Issue by hfahmy** [vinc3m1/RoundedImageView#118]
`RoundedImageView` is placed in the xml file and Glide is used to load image with crossfade animation enabled. A `ColorDrawable` is provided to Glide as a placeholder. However, loaded image is never shown. But when views are scrolled out of view and then back in, the image is shown.

This doesn't work:
```
                DrawableTypeRequest request = Glide.with(context).load(item.getImageRes());
                request.placeholder(placeholder).crossFade(2000);
                request.into(itemViewHolder.image);
```
When you are .asBitmap() to the builder, it works without the crossfade animation:
```
                DrawableTypeRequest request = Glide.with(context).load(item.getImageRes());
                request.placeholder(placeholder).crossFade(2000);
                request.asBitmap().into(itemViewHolder.image);
```

Any idea of how get around this issue while still retaining the crossfade animation?

**Comment by hfahmy** [comment]
Seems to work (partly) after updated to 2.2.0. Images loads even without calling .asBitmap() but kind of flickers and then starts cross fade animation.

**Comment by vinc3m1** [comment]
See https://github.com/vinc3m1/RoundedImageView/issues/122#issuecomment-172456922 for a possible solution.
