### ISSUE TITLE
Ion + RIV(oval=true) is not ovaled always

### ISSUE THREAD

**Issue by b1rdex** [vinc3m1/RoundedImageView#121]
My app has contact list. ListView avatar + name. Avatars are defined with remote HTTP URIs.
Avatars are loaded with Ion. Avatar has default value set.
Ion requests set to placeholder and error values with default avatar.
So we must get user avatar or default one.

And here is the problem: errored avatar is not always ovaled. Scrolling ListView to redraw items makes them oval.

This are errors:

look at 10008 & 10009 | look at 10011
------------ | -------------
![screenshot_2015-09-06-14-18-28](https://cloud.githubusercontent.com/assets/312855/9702478/7aad7b7e-54a2-11e5-969d-e14d77293271.png) | ![screenshot_2015-09-06-14-18-33](https://cloud.githubusercontent.com/assets/312855/9702479/7aae210a-54a2-11e5-8cb6-306e4f03beff.png)

These are redrawen good after scroll:

look at 10008 & 10009 | look at 10011
------------ | -------------
![screenshot_2015-09-06-14-18-36](https://cloud.githubusercontent.com/assets/312855/9702494/3df33d8a-54a3-11e5-9e2d-a3e370bc2466.png) | ![screenshot_2015-09-06-14-18-40](https://cloud.githubusercontent.com/assets/312855/9702495/3df3ad92-54a3-11e5-8e30-e650e3652e00.png)

This is my XML:
```XML
<com.makeramen.roundedimageview.RoundedImageView
        android:id="@+id/I_avatar"
        android:layout_width="@dimen/big_avatar_width"
        android:layout_height="@dimen/big_avatar_height"
        android:adjustViewBounds="true"
        android:contentDescription="User avatar"
        android:scaleType="centerCrop"
        android:src="@drawable/default_avatar"
        app:riv_oval="true" />
```

This method is called from contacts adapter `getView`:
```java
public static void setAvatarWithIon(final ImageView avatarView, final String avatarUri) {
    final int defaultAvatar = R.drawable.default_avatar;

    if (avatarUri != null && !avatarUri.isEmpty()) {
        Ion.with(avatarView)
                .placeholder(defaultAvatar)
                .error(defaultAvatar)
                .load(avatar)
        ;
    } else {
        avatarView.setImageResource(defaultAvatar);
    }
}
```

**Comment by mesropd** [comment]
I also have this issue and made circle image for placeholder and error for fast solution, but it is a workaround and I also want to know where is the problem?

**Comment by b1rdex** [comment]
I think the problem is in RIV: when ion request fails, RIV doesn't understand image resource changed, because R.id is same. So image redraws, but RIV don't ovals it assuming it hasn't changed.

**Comment by vinc3m1** [comment]
That's not true, as long as `riv_oval="true"` RIV will draw oval. I'm not sure how Ion works but it must be doing something incompatible with RIV.

**Comment by b1rdex** [comment]
Can you please make obstruction on how I can hack riv and edit it's code?
9 сент. 2015 г. 7:46 пользователь "Vince Mi" <notifications@github.com>
написал:

**Comment by ilyamuromets** [comment]
I have the same problem. I'm not using Ion. Instead I'm using custom implementation. My implementation asynchronously downloads icon and replaces placeholder image with TransitionDrawable.

**Comment by ilyamuromets** [comment]
I found a solution.
After image downloading complete I make it oval with:
```java
RoundedDrawable roundedDrawable = RoundedDrawable.fromBitmap(bitmap).setOval(true);
```
... and then I put oval image into TransitionDrawable.

**Comment by b1rdex** [comment]
Ilya, that's what I'm talking about — RIV is not detecting image update so
not applying oval transformation. But RIV creator just says "that's not
true and impossible". :-)

2015-11-24 17:33 GMT+10:00 ilyamuromets <notifications@github.com>:

**Comment by vinc3m1** [comment]
@b1rdex I don't think you understand, it's not possible for R.id.* to stay the same, those ids are hardcoded in your apk and must be unique or nothing else in the app would work. Ion is doing something that's incompatible with RIV, and RIV was not built with Ion compatibility in mind.

There is a picasso example though, and I'm sure you can do something similar to that for Ion, or do what @ilyamuromets is doing by re-wrapping the drawable ion gives you.

**Comment by b1rdex** [comment]
@vinc3m1 that's you don't understand. I didn't write `my R.id.* mutated`, I know that's not possible.
I wrote: `RIV is not detecting image update`. That's confirmed by 2 other guys. And you continue to say "impossible" and "you don't understand".
Ion is 1) sets placeholder 2) sets actual image or error image. Step 2 is broken in RIV for case "error image".
