### ISSUE TITLE
RoundedDrawable cannot be cast to android.graphics.drawable.BitmapDrawable

### ISSUE THREAD

**Issue by yesidlazaro** [vinc3m1/RoundedImageView#124]
Hi i trying yo use RoundedImageView with a picasso transformation that extract the palette using palette  support library .
Picasso transformation 
https://gist.github.com/yesidlazaro/1e601690a2c2a3f54cb6
 in the line 67 you can see 
 final Bitmap bitmap = ((BitmapDrawable) getImageView().getDrawable()).getBitmap(); // Ew!
this throw            
    java.lang.ClassCastException: com.makeramen.roundedimageview.RoundedDrawable cannot be cast to android.graphics.drawable.BitmapDrawable

this issue not happens when i use a normal ImageView from android package .

**Comment by vinc3m1** [comment]
You probably take some code from the RoundedTransformationBuilder instead: https://github.com/vinc3m1/RoundedImageView/blob/master/roundedimageview/src/main/java/com/makeramen/roundedimageview/RoundedTransformationBuilder.java#L160

Or case it to RoundedDrawable instead of BitmapDrawable.
