### ISSUE TITLE
ColorDrawable border width + default scaleType

### ISSUE THREAD

**Issue by mtiidla** [vinc3m1/RoundedImageView#126]
When I don't specify scaleType in the xml and use border_width with ColorDrawable, this is the result:
![roundedimageview](https://cloud.githubusercontent.com/assets/2339109/10478771/91c2ce66-7268-11e5-8a76-b7fe5830b59a.PNG)

However, when I set scaleType to fitCenter (that is also set by default) then it works as expected.

I think that these cool graphics appeared when including latest support or appcompat library.

**Comment by vinc3m1** [comment]
ColorDrawables are poorly supported; recommend vector drawables that you round yourself instead.
