### ISSUE TITLE
Doesn't work with scaleType(Matrix)

### ISSUE THREAD

**Issue by tplkn** [vinc3m1/RoundedImageView#131]
I need show images with translation and scale, so i use matrix. But RoundedImageView#setCornerRadius, RoundedImageView#setBorderWidth and RoundedImageView#setBorderColor have no effect

**Comment by duckinferno** [comment]
Same here.  Use case: my image view hosts an image larger than its bounds, which it translates as the user scrolls for a parallax and fake-blur effect.  

```
<com.makeramen.roundedimageview.RoundedImageView
        ...
        android:scaleType="matrix"
        app:riv_corner_radius="@dimen/card_corner_radius"
        app:riv_border_color="@color/white_8pc"
        app:riv_border_width="@dimen/card_stroke_width"/>

```

The image is not rounded, nor does any border appear.

**Comment by vinc3m1** [comment]
closing due to issue age
