### ISSUE TITLE
How do you not crop the image / icon? 

### ISSUE THREAD

**Issue by huteri** [vinc3m1/RoundedImageView#133]
Hi I use vector drawable icon as the source for rounded image view with mutate background, but the issue here is that the icon always get cropped on the rounded image view. How do you actually set icon to be centerInside? Adding paddings inside the icon is also not an easy way, since it's a vector, do you have any layout solution instead?

See the screenshot
![device-2015-12-21-160455](https://cloud.githubusercontent.com/assets/4598788/11927363/9da57ca8-a7fe-11e5-9cee-9f53cc718c83.png)

For the xml

```
<com.makeramen.roundedimageview.RoundedImageView
        android:id="@+id/iv_icon"
        android:layout_width="40dp"
        android:layout_height="40dp"
        android:layout_marginRight="16dp"
        tools:background="@color/primary_material_dark_1"
        android:layout_alignTop="@+id/tv_title"
        tools:src="@drawable/ic_cat_food_and_drink"
        android:scaleType="fitCenter"
        android:padding="5dp"
        android:transitionName="@string/fragment_image_trans"
        />
```

```
 holder.mIvIcon.setScaleType(ImageView.ScaleType.FIT_XY);
        holder.mIvIcon.setImageResource(order.getRelationships().getCategory().getData().getIcon());
        holder.mIvIcon.mutateBackground(true);
        holder.mIvIcon.setCornerRadius(0.3f);
        holder.mIvIcon.setBackgroundColor(color);
```

**Comment by vinc3m1** [comment]
That padding might be the issue here. Also looks like you have a border radius thickness somehow, try setting the border size to 0?

**Comment by huteri** [comment]
I've set the radius, but the problem still persists, here is my new code, I've cleaned for easy debugging.

```
<com.makeramen.roundedimageview.RoundedImageView
        android:id="@+id/iv_icon"
        android:layout_width="40dp"
        android:layout_height="40dp"
        tools:background="@color/primary_material_dark_1"
        android:layout_alignTop="@+id/tv_title"
        tools:src="@drawable/ic_camera_alt_24dp"
        android:transitionName="@string/fragment_image_trans"
        app:riv_oval="true"
        app:riv_border_width="0dp"
        app:riv_border_color="@color/black26"
        />
```

```
holder.mIvIcon.setImageResource(order.getRelationships().getCategory().getData().getIcon());
        holder.mIvIcon.mutateBackground(true);
        holder.mIvIcon.setBackgroundColor(color);
```

![device-2015-12-22-094634](https://cloud.githubusercontent.com/assets/4598788/11946790/ef10e630-a890-11e5-8590-301df7eb1b12.png)

I think it's a default behavior, it tends to crop the image, maybe adding an options to set image scaletype inside the view would help

**Comment by vinc3m1** [comment]
ScaleType should be supported, but VectorDrawable isn't directly supported, so I wouldn't be surprised if it's related to that

**Comment by vinc3m1** [comment]
closing due to issue age
