### ISSUE TITLE
Doesnt work with an ImageView in a Widget?

### ISSUE THREAD

**Issue by Orbyt** [vinc3m1/RoundedImageView#134]
I'm trying to use this to slightly round the corners of an ImageView in my Widget. Im loading the image with Picasso.

Using this code:

```
Transformation transformation = new RoundedTransformationBuilder()
                            .cornerRadiusDp(5)
                            .oval(false)
                            .build();

                    Picasso.with(context)
                            .load(url)
                            .transform(transformation)
                            .into(views, R.id.imageView, mAppWidgetIds);

```

basically this doesnt work for rounding the corners of the imageview. Im not sure why but would this not work with a ImageView in a Widget? Or if it does, how is it done?

**Comment by vinc3m1** [comment]
Does it work without the transformation? I wonder if remote views have some different logic, but I'm not familiar with widgets at all unfortunately.

**Comment by vinc3m1** [comment]
closing due to issue age
