### ISSUE TITLE
The corner radius left or right must be equal?

### ISSUE THREAD

**Issue by tracy1allen3** [vinc3m1/RoundedImageView#135]
When we set as follow :
.....
app:riv_corner_radius_top_left="15dp"
        app:riv_corner_radius_top_right="15dp"
....
it is ok.  But, when 
...
app:riv_corner_radius_top_left="15dp"
        app:riv_corner_radius_top_right="10dp"
...
it will be crashed.
so, it's the problem....

**Comment by vinc3m1** [comment]
The library doesn't support multiple radii because of performance reasons. They must all be the same or 0.
