### ISSUE TITLE
Round border with smaller bitmap

### ISSUE THREAD

**Issue by gnrcampos** [vinc3m1/RoundedImageView#136]
Is there a way of having the border drawn ALWAYS at the view's edge, even when the bitmap is smaller than it? I can't seem to find a way of doing this and I need it to be a circle even in those cases.

**Comment by tihomirleka** [comment]
Setting andorid:scaleType="center" should do the trick.

**Comment by lorenzos** [comment]
@tihomirleka Thanks! But **why** this works? And why it is different with `centerInside`?!? Readme says:

> * All `ScaleType`s:
>   * Borders are drawn at view edge, not bitmap edge
>   * Except on edges where the bitmap is smaller than the view*

**Comment by vinc3m1** [comment]
technical limitations make this a bit complicated, open to pull requests, but closing this issue due to age.
