### ISSUE TITLE
setBackgroundColor is not take into consideration in the rounded radius

### ISSUE THREAD

**Issue by kengleong** [vinc3m1/RoundedImageView#137]
when setBackgroundColor, the background color was right angle, ignoring the corner radius being set on the XML or programmatically coded. only setting the image works.

**Comment by jonasborggren** [comment]
This even happens for oval pictures. Whenever I set a background color to an image the ImageView becomes a square.

**Comment by vinc3m1** [comment]
should be resolved with #140
