### ISSUE TITLE
Please add some wiki

### ISSUE THREAD

**Issue by m4hmoud** [vinc3m1/RoundedImageView#138]
Firstly, thanks for the library.
But, do you mind adding a wiki to it? It would be really useful.

Libraries like this need a wiki to explain different properties. For example, how can I know what does "mutate_background" do?

**Comment by oliverwh** [comment]
Yeah, that would be much appreciated.

**Comment by vinc3m1** [comment]
There isn't much more than is in the readme, I can add some better comments though.
