### ISSUE TITLE
Rounded imageview circle

### ISSUE THREAD

**Issue by yasinkacmaz** [vinc3m1/RoundedImageView#143]
We have `app:riv_oval="true"` attribute but i need circle imageview.
Tried [this](https://github.com/hdodenhof/CircleImageView) but it can't provide `android:scaleType="fitXY"`. So anyone can help me please.

**Comment by bacy** [comment]
i have the same problem.

**Comment by avfernandezz** [comment]
I don't know if you still need a solution but you should make `app:riv_oval="false"` and `android:scaleType="centerCrop`. That worked for me, also consider moving the corner_radius to a higher value

**Comment by bacy** [comment]
a goog solution,thank you!
