### ISSUE TITLE
NoClassDefFoundError: com.makeramen.roundedimageview.R$styleable

### ISSUE THREAD

**Issue by fansmc** [vinc3m1/RoundedImageView#145]
NoClassDefFoundError: com.makeramen.roundedimageview.R$styleable my build info is :     compileSdkVersion 22
    buildToolsVersion "22.0.1"
 compile 'com.android.support:design:22+'
    compile 'com.android.support:recyclerview-v7:22+'
    compile 'com.android.support:cardview-v7:22+'

**Comment by drakmail** [comment]
In Android Studio clicking on "refresh" button solved problem for me:
![2016-03-25 23-42-27 instructor_card xml - instructortut - androidstudioprojects instructortut](https://cloud.githubusercontent.com/assets/869453/14053584/52af95f0-f2e3-11e5-942a-a352fb101afc.png)
