### ISSUE TITLE
Why I need to add Picasso Library in order to run ProGaurd

### ISSUE THREAD

**Issue by TonyHaddad91** [vinc3m1/RoundedImageView#147]
Hey, I'm using this Library and it working great but when i try to run ProGaurd 
I'm getting this error and it couldn't be resolved unless i added Picasso Library to my project 
Warning: com.makeramen.roundedimageview.RoundedTransformationBuilder$1: can't find superclass or interface com.squareup.picasso.Transformation

but i dont want to setup Picasso while i don't use it 
Any help?

**Comment by vinc3m1** [comment]
Oh that's because RoundedImageView can use Picasso if you want to. You can have proguard ignore it dontwarn on it.

**Comment by vinc3m1** [comment]
See this config from Signal:
https://github.com/WhisperSystems/Signal-Android/blob/master/proguard-rounded-image-view.pro
