### ISSUE TITLE
ScaleType CenterCrop doesn't work with RoundedTransformationBuilder

### ISSUE THREAD

**Issue by dflakoopa** [vinc3m1/RoundedImageView#149]
I used Picasso.transform(RoundedTransformationBuilder).fit().blahblah feature,
and my ImageView's scale type was set to centerCrop in xml.

However my image is forced to fit into ImageView, like FitXY type.

XML : 
<ImageView
                android:id="@+id/image"
                android:layout_width="64dp"
                android:layout_height="64dp"
                android:scaleType="centerCrop"
                android:layout_marginBottom="16dp"/>

Java :
public static final Transformation ROUND_TRANSFORM = new RoundedTransformationBuilder()
.scaleType(ImageView.ScaleType.CENTER_CROP)
.cornerRadiusDp(50)
.oval(false)
.build();

 ImageView profileImage = (ImageView) findViewById(R.id.image);
 Picasso.with(context)
                .load(photoUrl)
                .transform(ROUND_TRANSFORM)
                .fit()
                .into(profileImage);

**Comment by dflakoopa** [comment]
I didn't used the scaletype() feature. Sorry, my bad! No problem!

**Comment by wangyeming** [comment]
Me too~

**Comment by 6franek** [comment]
This doesn't work for me too 😕

**Comment by alikamts** [comment]
same +1

**Comment by alikamts** [comment]
Caused by: java.lang.NoClassDefFoundError: com.makeramen.roundedimageview.RoundedImageView$1 at com.makeramen.roundedimageview.RoundedImageView.setScaleType(RoundedImageView.java:197)
at android.widget.ImageView.<init>(ImageView.java:143)

**Comment by markuskallander** [comment]
Did anyone manage to find a workaround until this is fixed?

**Comment by vinc3m1** [comment]
picasso probably has its own scaletype setting in addition to the transformation
