### ISSUE TITLE
Border Shadow in the Corners

### ISSUE THREAD

**Issue by jngr** [vinc3m1/RoundedImageView#151]
Thank you for this excellent piece of software. It works very nicely though I’m facing an issue with one of my images:

With the following set in xml:

```
riv_border_width=”1dp”
riv_corner_radius=”10dp”
riv_border_color=”#ffffffff”
riv_mutate_background=”true"
```

and the following in code:

```
image.setImageDrawable(Drawable.createFromPath(path))
image.setBackgroundColor(color)
```

this particular image shows [thin shadows in the corners](http://snag.gy/Uh6fE.jpg).

**Comment by vinc3m1** [comment]
If you're making your own path you should probably just round the image yourself and not use RoundedImageView.
