### ISSUE TITLE
fitXY is not as expected with wide screen images in RoundedImageView

### ISSUE THREAD

**Issue by apps-appface** [vinc3m1/RoundedImageView#153]
ScaleTYpe fitxy is not working with wide screen images

**Comment by sunnydlee** [comment]
yes, I agree.
    Borders are drawn at view edge, not bitmap edge
    Except on edges where the bitmap is smaller than the view
    Borders are not scaled up/down with the image (correct width and radius are maintained);
so use bitmap of after sacle, than setImageDrable() .
`private void scaleFitXYIv(final ImageView iv, final int resID){
        iv.getViewTreeObserver().addOnGlobalLayoutListener(new ViewTreeObserver.OnGlobalLayoutListener()
        {
            @Override
            public void onGlobalLayout() {
                iv.getViewTreeObserver().removeGlobalOnLayoutListener(this);
//                System.out.println("onGlobalLayout width=" + iv.getWidth() + " height=" + iv.getHeight());
                Glide.with(CTX).load(resID).asBitmap().into(new SimpleTarget<Bitmap>() {
                    @Override
                    public void onResourceReady(Bitmap bitmap, GlideAnimation<? super Bitmap> glideAnimation) {
                        // 图片根据控件大小等比例缩放拉伸
                        float widthScale = iv.getWidth() * 1.0f / bitmap.getWidth();
                        float heightScale = iv.getHeight() * 1.0f / bitmap.getHeight();
                        // 设置长宽拉伸缩放比
                        Matrix matrix = new Matrix(); matrix.setScale(widthScale, heightScale);
                        // 拉伸缩放图片
                        Bitmap newBt = Bitmap.createBitmap(bitmap, 0, 0, bitmap.getWidth(), bitmap.getHeight(), matrix, true);
                        //设置拉伸后的图片
                        iv.setImageDrawable(new BitmapDrawable(newBt));
                    }
                });

            }
        });
    }`
