### ISSUE TITLE
Request: Add support for VectorDrawable/VectorDrawableCompat

### ISSUE THREAD

**Issue by creactivemobile** [vinc3m1/RoundedImageView#154]
Hello,

Right now, when we try to use a VD on the RoundedImageView the result is a non scaled image which gets all blurry.

Is there any plans to add support to VectorDrawable/VectorDrawableCompat? 😄

**Comment by vinc3m1** [comment]
Probably not, rounding vector drawables leads to a lot of bitmap and memory allocation which is pretty inefficient, they should be rounded at the vector level.
