### ISSUE TITLE
MutateBackground doesn't work if background not set in code

### ISSUE THREAD

**Issue by jon-adams** [vinc3m1/RoundedImageView#158]
The background mutation code is run in `updateBackgroundDrawableAttrs`. However, if the background is set via XML and the main image is set in code, `updateBackgroundDrawableAttrs` doesn't get called when it is needed.

I'm not totally sure if this is because the `updateBackgroundDrawableAttrs` call at object creation time is too early before the background is set, or if it is because the main image is set in code while the background is set via XML.

Either way, if one of a handful of properties are set in code later, then `updateBackgroundDrawableAttrs` is called and by then the XML background has been applied and the mutate works correctly.

Example psuedo code that is breaking:

``` xml
<com.makeramen.roundedimageview.RoundedImageView
    android:layout_width="96dp"
    android:layout_height="96dp"
    android:background="@android:color/white"
    app:riv_border_width="@dimen/logo_stroke_width"
    app:riv_mutate_background="true"
    app:riv_oval="true"
    tools:src="@drawable/logo"/>
```

``` java
mLogo.setBorderColor(someColor);
mLogo.setImageBitmap(bitmap);
```

This will use a full, square, white background (not mutated) while the supplied bitmap gets the correct border and mutation.

However, the background mutation will work as soon as you add the following right after the `setImageBitmap` call above:

``` java
mLogo.setBackground(new ColorDrawable(ContextCompat.getColor(this, android.R.color.white)));
```

**Comment by einverne** [comment]
Seems same issue as #130
