### ISSUE TITLE
Shared Element Transition bug

### ISSUE THREAD

**Issue by buutqn** [vinc3m1/RoundedImageView#164]
I have the following Layout inside my own gallery:

`<com.makeramen.roundedimageview.RoundedImageView
                android:id="@+id/imgView"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:transitionName="image"
                android:layout_centerInParent="true"
                android:adjustViewBounds="true"
                app:riv_corner_radius="4dp" />`

And this result when using the shared element transition:
![bug](https://cloud.githubusercontent.com/assets/15644387/16598663/667cec62-42d5-11e6-9c46-51972fb98bae.jpg)

if i click in "next button" or in the image to open in full screen and then back to the normal state or change it to normal ImageView, it works fine like all the next images:
![nobug](https://cloud.githubusercontent.com/assets/15644387/16598696/898547e0-42d5-11e6-9282-e40b0c544e5b.jpg)

The only problem is at the first time that opens, WHEN using the shared element transition, it bugs

**Comment by iTomkinas** [comment]
I have the same problem, any solutions?

**Comment by muehlemann** [comment]
Is there an update on this?

**Comment by MovementSpeed** [comment]
The solution to this is changing the base class of RoundedImageView from ImageView to AppCompatImageView.
