### ISSUE TITLE
I am not able to fit the entire image inside the ImageView. Only a portion of the image is getting displayed inside the ImageView. Please help

### ISSUE THREAD

**Issue by littleloulou** [vinc3m1/RoundedImageView#169]

**Comment by lph2012** [comment]
I try to change the scale Type ,but it don't work.

**Comment by tuomao** [comment]
i have the same problem too

**Comment by prazjain** [comment]
same problem. I thought this library supported all trade types. Can the author please respond. Thanks
@lph2012  @tuomao

**Comment by vinc3m1** [comment]
If you have specific repro steps that would help a lot.

**Comment by Denny966** [comment]
Got the same issue, just add an image to a imageview

**Comment by vinc3m1** [comment]
What version? Sample app and code? It's clearly not happening in the example app here so I have nothing to reproduce with.

**Comment by aprofessionalpirate** [comment]
Try remove app:riv_tile_mode="repeat" and see if it works.
