### ISSUE TITLE
can't load image source

### ISSUE THREAD

**Issue by ysemylord** [vinc3m1/RoundedImageView#170]
When use RoundedImageView
     Glide.with(context)
                .load(url)
                .placeholder(R.drawable.tab_account)
                .error(R.drawable.tab_account)
                .into(imageView);
thess code can't load Image,So I change this to 
        Glide.with(context)
                .load(url)
                .listener(new RequestListener<String, GlideDrawable>() {
                    @Override
                    public boolean onException(Exception e, String model, Target<GlideDrawable> target, boolean isFirstResource) {
                        return false;
                    }
                    @Override
                    public boolean onResourceReady(GlideDrawable resource, String model, Target<GlideDrawable> target, boolean isFromMemoryCache, boolean isFirstResource) {
                        imageView.setImageDrawable(resource);
                        return false;
                    }
                })
                .placeholder(R.drawable.tab_account)
                .error(R.drawable.tab_account)
                .into(imageView);
this  can load Image

**Comment by vinc3m1** [comment]
Seems like you have it working then?
Glide isn't fully supported yet, will look into it.
