### ISSUE TITLE
Are vector drawables not fully supported?

### ISSUE THREAD

**Issue by oradkovsky** [vinc3m1/RoundedImageView#174]
Scenario:

1. build.gradle: 

defaultConfig {
      vectorDrawables.useSupportLibrary = true
}

<com.makeramen.roundedimageview.RoundedImageView
      app:srcCompat="@drawable/ic_img_placeholder"
      ... />
       
Image is not rendered, no exceptions as well.

**Comment by torchhound** [comment]
I am experiencing similar issues. My vector drawables are displayed but they are very low resolution.
<img src="http://i.imgur.com/LB2Ma2E.png">

**Comment by oradkovsky** [comment]
You likely have blurry images because your app is supporting pre-lollipop and you are testing on pre-lollipop device. You need to use support library vectors handling to render vectors in good quality.

**Comment by torchhound** [comment]
Before I started using this library my vectors were very sharp. Do I need to do something specifically to get that quality back with this library?

**Comment by torchhound** [comment]
My bad, I needed to reimport the svgs at 300-500dp instead of the default 24.
