### ISSUE TITLE
selectableItemBackground

### ISSUE THREAD

**Issue by faridgh1991** [vinc3m1/RoundedImageView#178]
how can i add ripple effect on RoundedImageView? 
" android:background="?attr/selectableItemBackground" " and " android:clickable="true" "added in layout but not working.

**Comment by vinc3m1** [comment]
Ripples aren't supported out of the box similar to regular image views, see guidance online for examples: https://plus.google.com/+NickButcher/posts/dS8Qh7TC8Kq
