### ISSUE TITLE
doesn't support vector drawable?

### ISSUE THREAD

**Issue by lzl124631x** [vinc3m1/RoundedImageView#179]
By right clicking on folder drawable, clicking New, then Vector Asset, I added a Material Icon. RoundedImageView cannot render the icon as ImageView do.

```
<com.makeramen.roundedimageview.RoundedImageView
    android:layout_width="wrap_content"
    android:layout_height="wrap_content"
    app:srcCompat="@drawable/ic_lock_black_24dp"/>
<ImageView
    android:layout_width="wrap_content"
    android:layout_height="wrap_content"
    app:srcCompat="@drawable/ic_lock_black_24dp"/>
```

**Comment by vinc3m1** [comment]
This is true, vectors don't work well and should be rounded manually.

**Comment by programmerr47** [comment]
@lzl124631x You can do it from code:

```
Drawable iconDrawable = AppCompatResources.getDrawable(context, R.drawable.icon);
roundedImageView.setImageDrawable(iconDrawable);
```

**Comment by programmerr47** [comment]
@vinc3m1 What will happen if extend ```RoundedImageView``` from ```AppCompatImageView``` or create ```AppCompatRoundedImageView``` that extends ```AppCompatImageView```?

**Comment by vinc3m1** [comment]
VectorDrawables are fundamentally different from BitmapDrawables which this library is built for. You can maybe hack them to make them work, but you would lose all the advantages of having a VectorDrawable in the first place. It'd be slower and more memory intensive all around.
