### ISSUE TITLE
Image position changing on RecyclerView using GridLayoutManager

### ISSUE THREAD

**Issue by buddman1208** [vinc3m1/RoundedImageView#186]
[Android Emulator - Nexus_6P_API_25_5554 2017-05-09 오후 5_14_17.zip](https://github.com/vinc3m1/RoundedImageView/files/985933/Android.Emulator.-.Nexus_6P_API_25_5554.2017-05-09.5_14_17.zip)

(Attached ScreenShot Video)
I'm having issue which image position is changing when i scroll down and back in RecyclerView (used GridLayoutManager), only when i use RoundImageView. How can i avoid this situation?

**Comment by AbdallahAndroid** [comment]
i have the same problem
