### ISSUE TITLE
With some devices,drawRoundRect make crash

### ISSUE THREAD

**Issue by suncc001** [vinc3m1/RoundedImageView#188]
record_type=NATIVE_CRASH
app_version=2.3.6
error_thread=main
error_type=SIGSEGV(SEGV_MAPERR)
error_message=
error_address=0000000000000018

cause by:
         #00  pc 0016d426 /system/lib/libskia.so (S32_opaque_D32_nofilter_DX_neon(SkBitmapProcState const&, unsigned int const*, int, unsigned int*) +13) [armeabi-v7a::3cbbe8134d44f1624924b6d063332c6c]
         #01  pc 0017496c /system/lib/libskia.so (SkBitmapProcShader::shadeSpan(int, int, unsigned int*, int) +160) [armeabi-v7a::3cbbe8134d44f1624924b6d063332c6c]
         #02  pc 000acb5f /system/lib/libskia.so (SkARGB32_Shader_Blitter::blitRect(int, int, int, int) +406) [armeabi-v7a::3cbbe8134d44f1624924b6d063332c6c]
         #03  pc 000aa7ad /system/lib/libskia.so (SkBlitter::blitAntiRect(int, int, int, int, unsigned char, unsigned char) +52) [armeabi-v7a::3cbbe8134d44f1624924b6d063332c6c]
         #04  pc 000d6815 /system/lib/libskia.so (SuperBlitter::blitRect(int, int, int, int) +226) [armeabi-v7a::3cbbe8134d44f1624924b6d063332c6c]
         #05  pc 000d8b23 /system/lib/libskia.so [armeabi-v7a::3cbbe8134d44f1624924b6d063332c6c]
         #06  pc 000d9275 /system/lib/libskia.so (sk_fill_path(SkPath const&, SkIRect const*, SkBlitter*, int, int, int, SkRegion const&) +544) [armeabi-v7a::3cbbe8134d44f1624924b6d063332c6c]
         #07  pc 000d6d95 /system/lib/libskia.so (SkScan::AntiFillPath(SkPath const&, SkRegion const&, SkBlitter*, bool) +768) [armeabi-v7a::3cbbe8134d44f1624924b6d063332c6c]
         #08  pc 000d6e71 /system/lib/libskia.so (SkScan::AntiFillPath(SkPath const&, SkRasterClip const&, SkBlitter*) +32) [armeabi-v7a::3cbbe8134d44f1624924b6d063332c6c]
         #09  pc 000b6b15 /system/lib/libskia.so (SkDraw::drawPath(SkPath const&, SkPaint const&, SkMatrix const*, bool, bool) const +516) [armeabi-v7a::3cbbe8134d44f1624924b6d063332c6c]
         #10  pc 000a2f7d /system/lib/libskia.so (SkBitmapDevice::drawRRect(SkDraw const&, SkRRect const&, SkPaint const&) +52) [armeabi-v7a::3cbbe8134d44f1624924b6d063332c6c]
         #11  pc 000b0e77 /system/lib/libskia.so (SkCanvas::drawRRect(SkRRect const&, SkPaint const&) +158) [armeabi-v7a::3cbbe8134d44f1624924b6d063332c6c]
         #12  pc 000b00c7 /system/lib/libskia.so (SkCanvas::drawRoundRect(SkRect const&, float, float, SkPaint const&) +106) [armeabi-v7a::3cbbe8134d44f1624924b6d063332c6c]
         #13  pc 00077d37 /system/lib/libandroid_runtime.so [armeabi-v7a::1198cc070bf1dc1f873e2effb22838d9]
         #14  pc 0002034c /system/lib/libdvm.so (dvmPlatformInvoke +112) [armeabi-v7a::2fe4596e7bd19b6692a539f5db67f94e]
         #15  pc 00050fcf /system/lib/libdvm.so (dvmCallJNIMethod(unsigned int const*, JValue*, Method const*, Thread*) +398) [armeabi-v7a::2fe4596e7bd19b6692a539f5db67f94e]
         #16  pc 000297e0 /system/lib/libdvm.so [armeabi-v7a::2fe4596e7bd19b6692a539f5db67f94e]
         #17  pc 00030c6c /system/lib/libdvm.so (dvmMterpStd(Thread*) +76) [armeabi-v7a::2fe4596e7bd19b6692a539f5db67f94e]
         #18  pc 0002e304 /system/lib/libdvm.so (dvmInterpret(Thread*, Method const*, JValue*) +184) [armeabi-v7a::2fe4596e7bd19b6692a539f5db67f94e]
         #19  pc 00063715 /system/lib/libdvm.so (dvmIjava:
android.graphics.Canvas.native_drawRoundRect(Native Method)
android.graphics.Canvas.drawRoundRect(Canvas.java:1064)
com.makeramen.roundedimageview.b.draw(RoundedDrawable.java:293)
android.widget.ImageView.onDraw(ImageView.java:1019)
android.view.View.draw(View.java:14493)
android.view.View.buildDrawingCache(View.java:13706)
android.view.View.getDrawingCache(View.java:13491)
android.view.View.draw(View.java:14184)
android.view.ViewGroup.drawChild(ViewGroup.java:3103)
android.view.ViewGroup.dispatchDraw(ViewGroup.java:2940)
android.view.View.draw(View.java:14376)
android.view.ViewGroup.drawChild(ViewGroup.java:3103)
android.view.ViewGroup.dispatchDraw(ViewGroup.java:2940)
android.view.View.draw(View.java:14376)
android.view.ViewGroup.drawChild(ViewGroup.java:3103)
android.view.ViewGroup.dispatchDraw(ViewGroup.java:2940)
android.view.View.draw(View.java:14496)
android.view.View.draw(View.java:14378)
android.view.ViewGroup.drawChild(ViewGro

**Comment by azri92** [comment]
Any specific list of devices?
