### ISSUE TITLE
Transparent colors do not render correctly

### ISSUE THREAD

**Issue by liquidninja24** [vinc3m1/RoundedImageView#189]
Specifying a transparent color (`#990c121c`) using `setColorFilter`, or `setTintList`, does not render correctly. The alpha portion of the color is dropped and a solid tint is applied instead. 

This works correctly using the standard `ImageView` and `Drawable`, but is broken for `RoundedImageView` and `RoundedDrawable`.

**Comment by vinc3m1** [comment]
colorFilters and tintlists and not currently supported
