### ISSUE TITLE
The picture changed so bed when I changed ImageView's width and height in code

### ISSUE THREAD

**Issue by RosesJack** [vinc3m1/RoundedImageView#193]
code:         
isClick = !isClick;
                ViewGroup.LayoutParams layoutParams = mRoundImageView.getLayoutParams();
                if (isClick) {
                    layoutParams.height = layoutParams.height * 2;
                    layoutParams.width = layoutParams.width * 2;
                } else {
                    layoutParams.height = layoutParams.height / 2;
                    layoutParams.width = layoutParams.width / 2;
                }
                mRoundImageView.setLayoutParams(layoutParams);

**Comment by vinc3m1** [comment]
Closing issue due to age
