### ISSUE TITLE
Glide compatibility

### ISSUE THREAD

**Issue by AlexBlokh** [vinc3m1/RoundedImageView#196]
Hi!
I'm not really sure it has to be here, but there're an issue with Glide library producing Transition Drawable and this library not being able to round it.

There're mainly two pitfalls:
1 - Transition drawable leaves a hidden layer visible after crossfading(fading) drawable in (if you're familiar with overdrawing - you know what I mean)

2 - Transition drawable extends from LayerDrawable(which has horrible api as for me) and LayerDrawable doesn't set drawable ids by default and you can only set drawables by there indexes and index is only obtained by their ids

so, here are some screencasts. My implementation is on the left:

overdrawing
![overdraw](https://user-images.githubusercontent.com/4045375/30382169-1c0287c2-98a7-11e7-8480-529bcacafc70.gif)

rounding
![rounded_rorners](https://user-images.githubusercontent.com/4045375/30382137-00c9ac1a-98a7-11e7-9763-d212ea24d105.gif)

So I'm not sure where should I post my solutions. Should it be here, as a module or as a module of glide or as a separate gist

thx

**Comment by mwajeeh** [comment]
I am facing the same issue.

**Comment by vinc3m1** [comment]
As you saw in Glide's issue tracker, the efficient way to do rounding is to use a Transition like that in https://github.com/wasabeef/glide-transformations as referenced in the README.
