### ISSUE TITLE
Out of Memory Crashes

### ISSUE THREAD

**Issue by sajadmaster** [vinc3m1/RoundedImageView#199]
I used this library extensively because I loved it, but unfortunately, this library doesn't free the allocated memory after the usage is finished. This leads to out of memory crashes. I have at least 100 crash reports from my users so far. I had to change to Picasso library.

**Comment by vinc3m1** [comment]
This library doesn't manage memory or load images. Glide and Picasso have transformations that don't require RoundedImageView anymore.
