### ISSUE TITLE
can not use with glide

### ISSUE THREAD

**Issue by liyuyitong** [vinc3m1/RoundedImageView#206]
Use with glide, can not use placeholder default picture.if use placeholder ,round is not effect!

**Comment by aaironman** [comment]
I meet the same problem.Use with glide to load image in recyclerView,sometimes the round is not effect.
code:
Glide.with(mContext).load(topicModel.getTopic_icon().startsWith("http") ? topicModel.getTopic_icon() : Constants.BASEURL + topicModel.getTopic_icon()).centerCrop()
				.placeholder(R.color.gray_line_color).into(holder.ivBg);
![device-2018-02-27-144959](https://user-images.githubusercontent.com/5567894/36714647-fada9fbc-1bcd-11e8-8a62-c5f035429016.png)

**Comment by vinc3m1** [comment]
see the readme:

> Glide transforms are not supported, please use wasabeef/glide-transformations if you want to round images loaded from Glide.
