### ISSUE TITLE
Failed to resolve: roundedimageview

### ISSUE THREAD

**Issue by xinnuo** [vinc3m1/RoundedImageView#209]
When using this library,AS3.1 displays error messages Failed to resolve: roundedimageview

**Comment by W-quan** [comment]
+1

**Comment by zpliang94** [comment]
+1

**Comment by W-quan** [comment]
```
  jcenter()
  mavenCentral()
```

to

```
  mavenCentral()
  jcenter()
```

**Comment by xinnuo** [comment]
it works！

**Comment by UnateD** [comment]
Still Failed to resolve: roundedimageview even with

`mavenCentral()
  jcenter()`

**Comment by xinnuo** [comment]
maven { url "https://jitpack.io" } 加上这句
