### ISSUE TITLE
滚动视图中使用 快速滚动时 频繁gc

### ISSUE THREAD

**Issue by huanglonghan** [vinc3m1/RoundedImageView#210]
剪切圆角时 内部创建双份bitmap 不能在列表页使用 在快速滑动时 会创建大量bitmap  造成一直gc 建议使用bitmap池

**Comment by junquanvip** [comment]
的确，不适合在列表里使用

**Comment by vinc3m1** [comment]
If the underlying Drawable is a BitmapDrawable RoundedImageView will not create duplicates. If it's a different type of drawable it is not guaranteed to work well with RoundedImageView. This is noted in the Known Issues section of the README (https://github.com/vinc3m1/RoundedImageView#known-issues)
