### ISSUE TITLE
How to make only 2 corners rounded

### ISSUE THREAD

**Issue by Rehckover** [vinc3m1/RoundedImageView#211]
I need only 2 diagonal corners to be rounded not all. Is this possible?

**Comment by vinc3m1** [comment]
https://github.com/vinc3m1/RoundedImageView/blob/6a30cc9a7c71c2886d285d82a6b5e07b8bfcc591/roundedimageview/src/main/java/com/makeramen/roundedimageview/RoundedImageView.java#L463-L472
