### ISSUE TITLE
Is there any plan to add squircle image style in your library .. 

### ISSUE THREAD

**Issue by MinaSamirCap** [vinc3m1/RoundedImageView#212]
I just asking if you have any plane to preview the image view as a **squircle** image view like profile images in viber application ..  or like this 

![ic_ostn_new](https://user-images.githubusercontent.com/7923425/39257264-6cffcc74-48b1-11e8-9a55-0c42dbae826b.png)
![ic_user_profile](https://user-images.githubusercontent.com/7923425/39257265-6d35eee4-48b1-11e8-972e-a3121bf1b2c5.png)

**Comment by vinc3m1** [comment]
Probably not. Complex lines aren't hardware accelerated on all platforms, these are better pre-rendered or custom drawn to your needs.
