### ISSUE TITLE
XmlPullParserException

### ISSUE THREAD

**Issue by mahbubmukul** [vinc3m1/RoundedImageView#225]
<com.makeramen.roundedimageview.RoundedImageView
                                android:id="@+id/credit_card_image"
                                android:layout_width="match_parent"
                                android:layout_height="0dp"
                                android:layout_gravity="center_horizontal"
                                android:background="@drawable/semiround_white_default"
                                android:padding="2dp"
                                android:src="@drawable/ic_debit_credit_card_icon"
                                app:layout_constraintDimensionRatio="1:1"
                                app:riv_corner_radius="@dimen/value2" />

I am adding ic_debit_credit_card_icon.xml as source. It showing XmlPullParserException

**Comment by vinc3m1** [comment]
okay.

**Comment by vinc3m1** [comment]
https://stackoverflow.com/search?q=%5Bandroid%5D+xmlpullparserexception
