### ISSUE TITLE
ChangeBounds transition support

### ISSUE THREAD

**Issue by UvarovBoris** [vinc3m1/RoundedImageView#235]
Hi, is RoundedImageView support ChangeBounds transition?
I have FrameLayout with size W x H.  In it I have RoundImageView with size match_parent x math_parent and scaleType fitXY.
In some moment I call TransitionManager.beginDelayedTransition with ChangeBounds transition. And then change size of FrameLayout to 2W x 2H  - view increase, but RoundImageView not increase properly. It have init size and just fill empty space with border pixels.
![Screenshot_11](https://user-images.githubusercontent.com/15791158/59829967-50426380-9347-11e9-8e41-adb348da6e8d.png)

**Comment by Maliotis** [comment]
I have the same issue using the RoundedImageView as a sharedElement, changeBounds is the only one causing issues. Is there a workaround for it yet?

**Comment by UvarovBoris** [comment]
I just not used RoundImageView in this case.
