### ISSUE TITLE
Support rounded specific corners

### ISSUE THREAD

**Issue by baotiennv** [vinc3m1/RoundedImageView#241]
I want my image just rounded 2 left corner, so what to do? Is itsuported to do?

**Comment by XingSpace** [comment]
of course, RoundedImageView support specific settings of corner.

if you wanna setting parameters of corner in code:
RoundedImageView riv = new RoundedImageView(context);
riv.setCornerRadius(float topLeft
		,float topRight
		,float bottomLeft
		,float bottomRight)
