### ISSUE TITLE
错误: 已在类 styleable中定义了变量 RoundedImageView_android_scaleType

### ISSUE THREAD

**Issue by GitHubWorkAndroid** [vinc3m1/RoundedImageView#242]
在android 3.0 会出现
错误: 已在类 styleable中定义了变量 RoundedImageView_android_scaleType

**Comment by JimmyGoGoGo** [comment]
same...

**Comment by GitHubWorkAndroid** [comment]
3.3 去除 attr.xml 中重复的属性名称
在迁移到 AndroidX 之前，我们为自定义控件编写自定义属性时，可以与 android 已有的属性重名，但是，在 AndroidX 环境下不行了，如果存在重名的情况， 必然会报错——会提示你重复定义（详细错误信息没截图，但翻译过来就是重复定义了attr/xxx）。

错误示例：
<declare-styleable name="RoundImageView">
    ...
    <!-在迁移到androidx之前，这样写虽然不规范，但是能用，不报错->
    <attr name="textSize" format="Integer" />
    ...
</declare-styleable>
正确示例
<declare-styleable name="RoundImageView">
    ...
    <!-迁移到androidX之后，必须使用android:xxx 属性，不能定义android已有的属性->
    <attr name="android:textSize" />
    ...    
</declare-styleable>
关于重名属性，在 AndroidX 中不知道哪个控件中包含了一个 mode 属性，所以，如果之前你的自定义控件中有 <attr name="mode" format="xx取值类型" />，需要手动改成其他。或者通过 <attr name="android:xx属性" /> 的方式直接引用 android 中已经定义好的属性——当然了，前提是他们的取值类型一致。

作者：CnPeng
链接：<a href='https://www.jianshu.com/p/41de8689615d'>https://www.jianshu.com/p/41de8689615d</a>
来源：简书
著作权归作者所有。商业转载请联系作者获得授权，非商业转载请注明出处。
