### ISSUE TITLE
Rounded corners are disturbed when apply transition effect using Glide

### ISSUE THREAD

**Issue by asadmukhtar28** [vinc3m1/RoundedImageView#248]
When i apply transition using Glide then on some devices rounded corners are disturbed.
        `Glide.with(context).load(url).apply(requestOptions).transition(DrawableTransitionOptions.withCrossFade()).into(imageView);`

see the attached image. 

![20191205_130315 (1)](https://user-images.githubusercontent.com/22379988/70321228-997c6600-1848-11ea-9e50-ef4ecc5819f8.jpg)

**Comment by vinc3m1** [comment]
As noted in the Known Issues in the README:
> Glide transforms are not supported, please use wasabeef/glide-transformations if you want to round images loaded from Glide.
