### ISSUE TITLE
Poor Render Quality on Android Version 9

### ISSUE THREAD

**Issue by sorter** [vinc3m1/RoundedImageView#249]
I'm experiencing extremely poor quality rendering on Moto g(7) play Android version 9. 

This only occurs on this device/version, all others render normally. Here is a screenshot of ImageView side by side with RoundedImageView, I have also attached the image asset depicted in the screenshot.

```
        <com.makeramen.roundedimageview.RoundedImageView
            android:id="@+id/matrix_cell_avatar"
            android:layout_width="90dp"
            android:layout_height="90dp"
            android:layout_marginStart="5dp"
            android:layout_marginTop="5dp"
            android:layout_marginEnd="5dp"
            android:scaleType="fitCenter"
            app:riv_mutate_background="true"
            app:layout_constraintEnd_toEndOf="parent"
            app:layout_constraintStart_toStartOf="parent"
            app:layout_constraintTop_toTopOf="parent"
            app:riv_corner_radius="5dp"/>
```

Any guidance would be appreciated. 

**RoundedImageView**
![image](https://user-images.githubusercontent.com/763548/70828792-0f894b80-1dba-11ea-8675-c85c6a2aa51b.png)
----------
**ImageView**
![image](https://user-images.githubusercontent.com/763548/70828812-1e6ffe00-1dba-11ea-8902-657125004556.png)
-----
**image asset**
![air_conditioner](https://user-images.githubusercontent.com/763548/70828821-26c83900-1dba-11ea-93e6-4f264dd379b4.png)

**Comment by z423821123** [comment]
` mBitmapPaint = new Paint();
    mBitmapPaint.setStyle(Paint.Style.FILL);
    mBitmapPaint.setFlags(Paint.FILTER_BITMAP_FLAG);
    mBitmapPaint.setAntiAlias(true);
    mBitmapPaint.setDither(true);`

Add Paint.FILTER_BITMAP_FLAG in RoundedDrawable maybe be get better image quality
