### ISSUE TITLE
convert drawble image to bitmap

### ISSUE THREAD

**Issue by sami-soft** [vinc3m1/RoundedImageView#251]
hi , this error when convert  drawble image to bitmap :

com.makeramen.roundedimageview.a cannot be cast to android.graphics.drawable.BitmapDrawable

BitmapDrawable drawable = (BitmapDrawable) Profile_image.getDrawable();
Bitmap bmp = drawable.getBitmap();

please help me

**Comment by vinc3m1** [comment]
RoundedDrawable is not a BitmapDrawable.

https://github.com/vinc3m1/RoundedImageView/blob/ace0766bccadf148b294719fd1622a2aeefea107/roundedimageview/src/main/java/com/makeramen/roundedimageview/RoundedDrawable.java#L44
