### ISSUE TITLE
Fatal Exception: java.lang.OutOfMemoryError

### ISSUE THREAD

**Issue by rezaiyan** [vinc3m1/RoundedImageView#253]
Failed to allocate a 16777228 byte allocation with 14638304 free bytes and 13MB until OOM
com.makeramen.roundedimageview.RoundedDrawable.drawableToBitmap

`
com.makeramen.roundedimageview.RoundedDrawable.drawableToBitmap (RoundedDrawable.java:134)
com.makeramen.roundedimageview.RoundedDrawable.fromDrawable (RoundedDrawable.java:117)
com.makeramen.roundedimageview.RoundedImageView.setImageDrawable (RoundedImageView.java:233)
`

**Comment by Mohsen-Nejati** [comment]
you just need have a rule for your image >>> max image size (to NOT see fatal exception any more) : 660 * 700

**Comment by vinc3m1** [comment]
You're not using a bitmapdrawable, as documented in the [known issues](https://github.com/vinc3m1/RoundedImageView#known-issues) other drawables result in creating large bitmaps and often have better ways to creating rounding than this library.
