### ISSUE TITLE
Out of Memory Error in resolveBackgroundResource

### ISSUE THREAD

**Issue by aligokdemir** [vinc3m1/RoundedImageView#255]
com.makeramen.roundedimageview.RoundedImageView.resolveBackgroundResource (RoundedImageView.java:307)

this line gives out of memory error.

**Comment by vinc3m1** [comment]
Not helpful without a full stacktrace.

You're probably using a non-bitmap drawable (e.g. vector drawble) which causes RIV to convert to a bitmap and uses a lot of memory, or your underlying bitmap is too large and would be causing an OOM anyway even with a regular ImageView. It's not recommended to use RIV with non-bitmap drawbles.
