### ISSUE TITLE
Losing Fade-in Animation when used with Picasso

### ISSUE THREAD

**Issue by diozz** [vinc3m1/RoundedImageView#257]
I used to get a fade-in kind of transition when an image is loaded using _Picasso_ into a regular `ImageView` with something like:

    Picasso.get()
     .load(event.PosterURL)
     .placeholder(R.drawable.back_image)
     .into((ImageView) child.findViewById(R.id.EventPoster));

Same code works with `RoundedImageView`, but the fade-in animation is gone and the placeholder is replaced promptly. How an I achieve this animation?

**Comment by vinc3m1** [comment]
See the README for Picasso usage: https://github.com/vinc3m1/RoundedImageView#picasso
