### ISSUE TITLE
RoundedImageView not working Glide transition animation and rounded corner broken!

### ISSUE THREAD

**Issue by Yakostya-art** [vinc3m1/RoundedImageView#263]
After 

Glide.with(context).load(R.drawable.mySquareImage).transition(DrawableTransitionOptions.withCrossFade(1000)).into(roundedImageView)

Not working transition animation and the image becomes square, corner rounding disappears.

**Comment by vinc3m1** [comment]
As noted in the README: https://github.com/vinc3m1/RoundedImageView#known-issues

> Glide transforms are not supported, please use [wasabeef/glide-transformations](https://github.com/wasabeef/glide-transformations) if you want to round images loaded from Glide.
