### ISSUE TITLE
android:scaleType Not working in new version

### ISSUE THREAD

**Issue by horsehead1111** [vinc3m1/RoundedImageView#269]
scaleType Not working in new version

**Comment by forceporquillo** [comment]
same issue

**Comment by OneGreenHand** [comment]
自己加一个吧
<attr name="riv_scaleType">
            <enum name="matrix" value="0" />
            <enum name="fitXY" value="1" />
            <enum name="fitStart" value="2" />
            <enum name="fitCenter" value="3" />
            <enum name="fitEnd" value="4" />
            <enum name="center" value="5" />
            <enum name="centerCrop" value="6" />
            <enum name="centerInside" value="7" />
        </attr>
然后改一下代码
int index = a.getInt(R.styleable.RoundedImageView_riv_scaleType, 3);

**Comment by OneGreenHand** [comment]
然后布局中使用
app:riv_scaleType="fitXY"
