### ISSUE TITLE
Different results when using RoundedDrawable/Transformation and RoundedImageView

### ISSUE THREAD

**Issue by marwinxxii** [vinc3m1/RoundedImageView#50]
I'm trying to draw people photos in circle (like in G+)

If I define RoundedImageView in xml:

```
<com.makeramen.RoundedImageView
        android:id="@+id/image3"
        android:layout_width="@dimen/size"
        android:layout_height="@dimen/size"
        android:src="@drawable/marcus"
        ci:border_color="@color/ring"
        ci:border_width="@dimen/width"
        ci:corner_radius="@dimen/radius"/>
```

With next parameters:

```
<color name="ring">#ff0000</color>
<dimen name="size">65dp</dimen>
<dimen name="radius">32.5dp</dimen><!-- size /2 -->
<dimen name="width">4dp</dimen>
```

Photo is drawn as expected (photo 3).

But if I'm trying to load image using Ion+Transformation or from RoundedDrawable

```
RoundedDrawable.fromDrawable(dr))
                .setBorderWidth(res.getDimensionPixelSize(R.dimen.width))
                .setCornerRadius(res.getDimensionPixelSize(R.dimen.radius))
                .setBorderColor(res.getColor(R.color.ring))
                .setOval(false)
```

Photo is drawn not in circle, but as rectangle with rounded corners. Also, you may notice, that width of border is also different for circle and rectangle.

Example:
First is using RoundedDrawable, second is using Ion transformation and third is RoundedImageView
![marcus](https://cloud.githubusercontent.com/assets/679204/3963720/fa1dc798-277f-11e4-9a7c-24182a2e65e1.jpg)

I tried setting bounds for drawables but that didn't help me.

I can provide whole test project.

I can solve this issue by defining bigger radius when using transformation, but it seems weird for me.

**Comment by sushantpaygude** [comment]
I am not able to fit the entire image inside the imageview. Only a portion of the image is displayed inside the imageview. What should be done to fit the entire image inside?
