### ISSUE TITLE
Support for Volley?

### ISSUE THREAD

**Issue by townsfolk** [vinc3m1/RoundedImageView#63]
First off, thank you very much for putting this into a maven-ized library.

With the official Android documentation mentioning volley (maybe even recommending it), and the open bug for fixing setImageUri, is there any possibility to add support for Volley? Or do you have any advice on using Volley to download and manage the bitmaps for the rounded image view? Perhaps a way to delegate bitmap retrieval and view re-use to Volley's NetworkImageView?

Thanks for any help.

**Comment by ameen-sarsour** [comment]
Hi,
I've create a class make rounded image, it's extend from NetworkImageView, please check it
https://gist.github.com/ameen-sarsour/5fecb7052eaa719d330b

**Comment by ongakuer** [comment]
I've created another one which extend from RoundedImageView
https://gist.github.com/ongakuer/3df480c28540b4eb779d

**Comment by vinc3m1** [comment]
@ameen-sarsour your solution is definitely not very viable since you're creating an extra bitmap (double memory use) and not re-using any code from this library, mostly RoundedDrawable.

@ongakuer this looks feasible, if you want to open a pull request we can definitely try it out.

**Comment by ongakuer** [comment]
@vinc3m1 
It's not necessary to open a pull request.  It depends on Volley.

**Comment by vinc3m1** [comment]
Since it's a separate class, it woudln't hurt to include volley as a `provided` dependency so people can use it if they'd like.

**Comment by ongakuer** [comment]
@vinc3m1 
But there is no official Maven repo for [Volley](https://android.googlesource.com/platform/frameworks/volley
)…

**Comment by vinc3m1** [comment]
True... I'll mark this closed then and people can reference gists.
