### ISSUE TITLE
tag name is not correct

### ISSUE THREAD

**Issue by anderson916** [vinc3m1/RoundedImageView#70]
when I use this tag name: com.makeramen.roundedimageview.RoundedImageView,  the compiler will complain it can't find the class. After changing it to com.makeramen.RoundedImageView, it works.

**Comment by vinc3m1** [comment]
thanks @anderson916 I am playing with package names and considering changing it and changed it in code but didn't push up an update yet (haven't decided if I want to keep the change). Good catch!
