### ISSUE TITLE
setCornerRadius(float/int) misleading

### ISSUE THREAD

**Issue by zudov** [vinc3m1/RoundedImageView#71]
Hi.

I was trying out the library, so I followed the README, but got a problem with corner radius:

```java
riv.setCornerRadius(10)
```
Was failing with ResourceNotFound exception. From the source code I found out that `setCornerRadius(float)` and `setCornerRadius(int)` work very differently, and in order to directly set the corner radius one should make sure that the floatish method is used.

I find it very misleading, perhaps method `setCornerRadius(int resId)` should be changed to `setCornerRadiusFromResource(int resId)`. I understand that it might not be possible at the moment because of backward compatibility, but please consider that change on major update.

I'll also submit a PR with the change in README's code example.

**Comment by vinc3m1** [comment]
hm I see your point, there will probably be some minor breaking changes in the next build anyway, so this might not be bad. I'd probably name it `setCornerRadiusRes` though.
