### ISSUE TITLE
RoundedImageView does not support ColorFilters / tint color

### ISSUE THREAD

**Issue by martyglaubitz** [vinc3m1/RoundedImageView#73]
While the RoundedDrawable does implement setColorFilter, it does not seem that an tint/colorfilter applied to the RoundedImageView has any effect.

**Comment by vinc3m1** [comment]
can you test out the latest snapshot and make sure it works as expected?

**Comment by martyglaubitz** [comment]
@vinc3m1 sorry, i had no time to test this, but i totally trust you that this's fixed ^^

**Comment by sbatezat** [comment]
It seems to work on Nexus 4 / Nexus 5 but it doesn't work on xiaomi mi2. Did'nt had other devices to test on, sorry
On mi-2, the color filter is applied to the square image virw instead of the circle part.
 I'm tried with two fonctions:

Imageview.setColorFilter and 
Imageview.getDrawable().setColorFilter

**Comment by softmarshmallow** [comment]
solutions?

**Comment by lzbrady** [comment]
I believe I am running into this issue. Can't seem to get a tint over the top of the image.

XML:
`    <com.makeramen.roundedimageview.RoundedImageView
        android:id="@+id/backgroundIV"
        android:layout_width="match_parent"
        android:layout_height="140dp"
        android:adjustViewBounds="true"
        android:alpha="0.6"
        android:background="@color/OrangeBtn"
        android:scaleType="centerCrop"
        android:src="@drawable/bg_image"
        android:tint="@color/OrangeTransparent"
        android:tintMode="src_atop"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintTop_toTopOf="parent"
        app:riv_corner_radius="8dip"
        app:riv_mutate_background="true"
        app:riv_oval="false" />
`

I would expect the OrangeTransparent color to be set on top of the image, but this is not the case.
