### ISSUE TITLE
Two concentric borders if view has both background and padding

### ISSUE THREAD

**Issue by guilhermearaujo** [vinc3m1/RoundedImageView#74]
I'm using an image with transparent background, and I'm setting the background color through code.
However, if I add padding to the view, there will be two borders, one around the view box, and another, smaller, around the padded image. This second border shouldn't exist.

![](http://cl.ly/image/1w283F3p3O0M/Image%202015-01-09%20at%205.00.29%20PM.png)

```xml
<com.makeramen.RoundedImageView
        android:layout_width="30dp"
        android:layout_height="30dp"
        android:padding="5dp"
        app:riv_corner_radius="30dp"
        app:riv_border_width="2dp"
        app:riv_border_color="#CCCCCC"
        app:riv_mutate_background="true" />```

**Comment by vinc3m1** [comment]
Actually backgrounds by default are not affected by padding, so in this case the result is correct.

1. With `riv_mutate_background`, a border is added to the background which is not affected by padding, so the large gray border is added.
2. The foreground image is padded and mutated as well, so you the smaller border is created.

If you only want the outer border I would suggest using the `RoundedDrawable` directly and setting it on a normal `ImageView` with padding and not use `RoundedImageView` at all.
