### ISSUE TITLE
RoundedImageView does not support background

### ISSUE THREAD

**Issue by wangdong20** [vinc3m1/RoundedImageView#75]
Here is code:
<com.makeramen.roundedimageview.RoundedImageView
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:src="@drawable/card_send_cash_bg"
        roundedimageview:riv_corner_radius="30dp" />

It work here.

But when i use this
<com.makeramen.roundedimageview.RoundedImageView
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:background="@drawable/card_send_cash_bg"
        roundedimageview:riv_corner_radius="30dp" />

It does not work.

When i inflate the RoundedImageView and setBackgroudDrawable() or setBackground() in RoundedImageView , it not work.

Does it really not support the background attribute?

**Comment by vinc3m1** [comment]
What do you mean by "It does not work.", do you want the background rounded too? Did you try `roundedimageview:riv_mutate_background="true"` or `riv.mutateBackground(true);`?

**Comment by wangdong20** [comment]
Yes, you are right.
roundedimageview:riv_mutate_background="true"
It worked here.  Thanks for your answer.

**Comment by osrl** [comment]
Why doesn't this work for me?



        <com.makeramen.RoundedImageView
            android:id="@+id/room_service_imageView"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_marginBottom="10dp"
            android:background="#FFFFFF"
            android:padding="14dp"
            android:src="@drawable/icon"
            app:riv_mutate_background="true"
            app:riv_oval="true"/>

What I want is this:
![screen shot 2015-02-28 at 18 49 49](https://cloud.githubusercontent.com/assets/781453/6427167/32743020-bf81-11e4-8225-262cbfd27259.png)

This is what I get:
![screen shot 2015-02-28 at 18 49 23](https://cloud.githubusercontent.com/assets/781453/6427166/3270bb16-bf81-11e4-8b09-bbd902d13fac.png)

**Comment by bunq-android** [comment]
I have the same problem.

**Comment by osrl** [comment]
Setting the attributes programatically worked for me.

**Comment by wangdong20** [comment]
It seems Rounded backgrounds don't work in ColorDrawable

**Comment by schwiz** [comment]
They work in 5.0 but not anything sooner than that...

**Comment by vinc3m1** [comment]
Please add any further comments and track this issue in #80. Have we narrowed it down to only colordrawables in background? I'd be interested in a repro case if someone can provide one.

**Comment by schwiz** [comment]
I was remembering wrong. It is ShapeDrawable that isn't honored in the background image until 5.0

setBackgroundDrawable(new OvalShape()) works great 5.0 for a cirlce background color (actually required if you want native shadows on a circle shape) However it renders as a square on 4.4-

**Comment by zsoltk** [comment]
This bug has to do something with the order of calling the setters on the RounderImageView.

If you use it as @osrl wrote, it works just fine:
```
mImageView.mutateBackground(true);
mImageView.setOval(true);
mImageView.setBackgroundColor(Color.parseColor("#333333"));
```

 If, however, you put mutateBackground after setting the background, it will not:
```
mImageView.setOval(true);
mImageView.setBackgroundColor(Color.parseColor("#333333"));
mImageView.mutateBackground(true);
```

Why this happens is beyond my scope of understanding, but this would explain why defining the attributes in xml doesn't work:

```
public RoundedImageView(Context context, AttributeSet attrs, int defStyle) {
    super(context, attrs, defStyle);
```

The constructor calls super() first (which will set the inherited params like backgroundcolor etc.), and it is only later that custom params are processed.

I hope this helps finding the source of the bug.

**Comment by bajicdusko** [comment]
Also if you set `android:scaleType="centerInside"` to your RoundedImageView element, it will affect background as well and it won't draw, even if you sort setters as @zsoltk mentioned above.
