### ISSUE TITLE
No rounding when used with Glide

### ISSUE THREAD

**Issue by gillde** [vinc3m1/RoundedImageView#76]
I am trying to use this View in conjunction with the image library Glide (similar to Picasso).

Scenario is using one RoundedImageView per item within a listview.

Everything works fine but when I am using a placeholder then the loaded image first gets drawn as a square but when I make the view disappear and then reappear (pulling down and then up, for example) the image is drawn correctly (that is, as a circle with a border)

```
ImageView imageViewContactPhoto = ViewHolder.get(view, R.id.imageView_person);
Glide.with(context)
                .load(Uri.parse(photoThumbnailURI)) //URI to image from local addressbook
                .placeholder(R.drawable.icon_emptyperson_filled) //without this line everything works fine
                .error(R.drawable.icon_emptyperson_filled)
                .into(imageViewContactPhoto);
```
```
<com.makeramen.RoundedImageView
            android:id="@+id/imageView_person"
            android:layout_width="48dp"
            android:layout_height="48dp"
            app:riv_border_width="2dp"
            app:riv_border_color="@android:color/white"
            app:riv_oval="true"/>
```
any idea to why this happens?

It seems like its working if I set a placeholder but also call .dontAnimate()
```
Glide.with(context)....placeholder(R.drawable.icon_emptyperson_filled).dontAnimate()...
```

**Comment by vinc3m1** [comment]
Glide probably uses a special subclass of Drawable to do the animation that `RoundedImageView` doesn't support. We get around this in Picasso with a [custom Transformation](https://github.com/vinc3m1/RoundedImageView#usage), there's probably something similar in glide we can do.

**Comment by gillde** [comment]
Thanks for your answer. 

I am not very used to custom Drawables/Transformations, so I will just leave it without the animation.

I just thought Id share this with you :)

**Comment by vinc3m1** [comment]
I believe [Custom Targets](https://github.com/bumptech/glide/wiki/Custom-targets) will solve this problem.

**Comment by guitcastro** [comment]
Just use `asBitmap` :

```
Glide.with(context)
                .load(Uri.parse(photoThumbnailURI)) //URI to image from local addressbook
                .asbBitmap()
                .placeholder(R.drawable.icon_emptyperson_filled) //without this line everything works fine
                .error(R.drawable.icon_emptyperson_filled)
                .into(imageViewContactPhoto);

```

**Comment by asker517** [comment]
@guitcastro thanks so much!! nice !

**Comment by miraclebg** [comment]
@guitcastro Thanks for saving another XYZ hours ;)

**Comment by zxzx74147** [comment]
@guitcastro Thanks !

**Comment by levais** [comment]
@guitcastro Saving my day! Thank you

**Comment by YunanChen** [comment]
@guitcastro Thanks!
