### ISSUE TITLE
Shadow effect in RoundedImageView

### ISSUE THREAD

**Issue by vishwasdoth** [vinc3m1/RoundedImageView#77]
How can I add shadow in roundedImageView?

**Comment by vinc3m1** [comment]
Shadows are not currently supported directly on RoundedImageView because it changes the view bounds. I'm open to exploring options though.

**Comment by schwiz** [comment]
vinc3m1 I would say shadow should effect the view bounds exactly the same way as the border does now. Just basically shrink down the image to fit everything. This is basically what I've done to get a similar effect.

     // in constructor
     if(mShadow){
          mPaddingPaint.setShadowLayer(sShadowSize, 0.0f, 0.0f, Color.BLACK);
     }

    @Override
    protected void onBoundsChange(Rect bounds) {
        super.onBoundsChange(bounds);
        mShadowRectF.set(bounds);
        mPaddingRectF.set(bounds);
        mBitmapRectF.set(bounds);
        mBitmapRectF.inset(sPadding, sPadding);
        if(mShadow){
            mBitmapRectF.inset(sShadowSize*2, sShadowSize*2);
            mPaddingRectF.inset(sShadowSize*2, sShadowSize*2);
            mShadowRectF.inset(sShadowSize, sShadowSize);
            RadialGradient gradient = new RadialGradient(bounds.right / 2, bounds.bottom / 2,
                    bounds.right / 3, new int[] {
                    Color.BLACK, Color.TRANSPARENT}, null, Shader.TileMode.CLAMP);
            mShadowPaint.setShader(gradient);
        }
    }

    @Override
    public void draw(Canvas canvas) {
        if(mShadow) canvas.drawOval(mShadowRectF, mShadowPaint);
        canvas.drawOval(mPaddingRectF, mPaddingPaint);

        canvas.drawOval(mBitmapRectF, mBitmapPaint);
    }

**Comment by vinc3m1** [comment]
I'm open to a pull request if it doesn't affect non-shadow usage.

**Comment by schwiz** [comment]
Ok I'll look into it for sure. I actually use your implementation when I don't want shadows and mine when I do right now :-)  Would be nice to combine them though.

**Comment by Rainer-Lang** [comment]
Shadows would be pretty nice.

**Comment by Rainer-Lang** [comment]
Any news?

**Comment by artaex** [comment]
What's the status on this?

**Comment by vinc3m1** [comment]
I have no plans to support this. Open to a pull request if someone really wants it and it doesn't affect any existing APIs.
