### ISSUE TITLE
Do not work with amulyakhare/TextDrawable

### ISSUE THREAD

**Issue by byandby** [vinc3m1/RoundedImageView#78]
imageView = (RoundedImageView) findViewById(R.id.imageView1);
int mineColor = getResources().getColor(R.color.thumbnail_bg_one);
TextDrawable drawable;
drawable = TextDrawable.builder().buildRoundRect("R", mineColor, 6);
imageView.setImageDrawable(drawable);

The RoundedImageView only has a background but not text is draw.

**Comment by vinc3m1** [comment]
You don't need to use RoundedImageView since TextDrawable already supports rounded corners. Just use a normal ImageView.
