### ISSUE TITLE
Implement onSizeChanged

### ISSUE THREAD

**Issue by Queatz** [vinc3m1/RoundedImageView#79]
Awesome library!  Noticed one thing, when changing the view orientation the images did not resize correctly.  Should be a simple fix.

http://developer.android.com/reference/android/view/View.html#onSizeChanged(int, int, int, int)

**Comment by vinc3m1** [comment]
Are you doing some custom like `android:configChanges`? I haven't seen this happen myself. If you have an example that will reproduce that would help.

**Comment by Queatz** [comment]
@vinc3m1 Yep, I don't want to recreate the view each time the view changes.  It's literally just a RoundedImageView in an adapter, nothing special at all.  It also isn't updating when the adapter recycles into a new cell of a different size.  I'm using the centerCrop scaleType.

**Comment by vinc3m1** [comment]
Can you confirm that the images resize correctly with a regular ImageView? If that's the case there may be a bug, but I doubt it's in `onSizeChanged` since ImageView doesn't implement that either.

**Comment by Queatz** [comment]
It worked fine with just the ImageView.  The matrix just doesn't seem to be adjusting itself when the size changes.  This is a vid of what's happening: https://www.youtube.com/watch?v=TCJs2pTGnQ4 (when I refresh it resets the view to how it should've looked after the orientation change.)

**Comment by vinc3m1** [comment]
Hm, I can't seem to reproduce, can you maybe provide an example?

Also are you using some library to load this image? And do you have scaletype set as center_crop?

It's possible that when you load the image in portrait the bitmap size is resized to fit the portrait view, and isn't resized again in landscape.

**Comment by vinc3m1** [comment]
Closing since I haven't heard anything in a while. Also the rendering logic has been rewritten since then. Feel free to re-open if issue still persists.

**Comment by steven274** [comment]
I have the same problem when using with android:configChanges="orientation"

**Comment by vinc3m1** [comment]
Can you provide a repro case example?
