### ISSUE TITLE
CENTER_CROP is not precisely centered if border_width > 0 

### ISSUE THREAD

**Issue by yeusin** [vinc3m1/RoundedImageView#8]
It should be translate along with border_width to be drawn correctly.

RoundedDrawable.java

private void setMatrix() {
...
...
CENTER_CROP:
...
...
mShaderMatrix.postTranslate((int) (dx + 0.5f) + mBorderWidth, (int) (dy + 0.5f) + mBorderWidth); // Translate by border_width to both x, y.

**Comment by alwaysthecritic** [comment]
I'm still seeing this bug, so I presume this change never got made. When I use the following XML, the white border causes the image itself to not be centred: it's moved down and to the right by the looks of it. In our case this makes the border feature unusable, which is a shame.

    <com.makeramen.roundedimageview.RoundedImageView
                xmlns:app="http://schemas.android.com/apk/res-auto"
                android:layout_width="60dp"
                android:layout_height="60dp"
                android:src="@drawable/profile_avatar_default"
                android:scaleType="centerCrop"
                app:riv_oval="false"
                app:riv_corner_radius="30dp"
                app:riv_border_width="3dp"
                app:riv_border_color="@color/white"/>

**Comment by alwaysthecritic** [comment]
A little experimentation shows that this would work, where we simply add /2 after each mBorderWidth, to ensure the image is centred within the border:

    mShaderMatrix.postTranslate((int) (dx + 0.5f) + mBorderWidth/2, (int) (dy + 0.5f) + mBorderWidth/2);

An alternative approach would be to scale the image down a bit (by border width presumably), so the border doesn't overlap its edges at all.

**Comment by vinc3m1** [comment]
I actually think borderWidth should not be part of the postTransate at all in this case since mBorderRect is already inset by the necessary amount. I think I will just remove that.

There will still needs to be overlap, which is needed for a clean line between the border and the image. Otherwise you see small bits of white between the border and the image due to antialiasing.

**Comment by vinc3m1** [comment]
Here's a test with super thick and transparent borders.

Current Behavior
![screen shot 2015-06-14 at 7 50 31 pm](https://cloud.githubusercontent.com/assets/498852/8152226/54d08eba-12cf-11e5-95fd-75ab3f29c52f.png)

New behavior:
![screen shot 2015-06-14 at 7 52 23 pm](https://cloud.githubusercontent.com/assets/498852/8152227/54d256a0-12cf-11e5-9916-efb78ccac21d.png)

**Comment by alwaysthecritic** [comment]
Hmmm - for me this fix doesn't work correctly, but my suggestion with mBorderWidth/2 does. Maybe there's something screwy with my images, but I don't believe so. I'm using avatar images, that by default are a centred, symmetrical graphic (e.g. the Twitter egg in this example) but I can see that the image does not end up centred within the border with your fix.

![device-2015-06-15-092812](https://cloud.githubusercontent.com/assets/2168000/8155929/ea9f0b30-1340-11e5-8e1b-2ac7a2ef0236.png)

**Comment by vinc3m1** [comment]
Hm, that looks to be off more than borderwidth/2... Any chance you can provide some sample code to reproduce?

**Comment by alwaysthecritic** [comment]
If I add in + mBorderWidth/2 to the translation it appears to centre perfectly.

![device-2015-06-15-094751](https://cloud.githubusercontent.com/assets/2168000/8156315/bfd8198e-1343-11e5-8189-849973578a61.png)

The XML in question is as follows:

            <com.makeramen.roundedimageview.RoundedImageView
                xmlns:app="http://schemas.android.com/apk/res-auto"
                android:id="@+id/avatar_image"
                android:layout_width="60dp"
                android:layout_height="60dp"
                app:riv_corner_radius="30dp"
                android:layout_gravity="center"
                android:layout_marginTop="15dp"
                style="@style/BigAvatarWithBorder"/>

A whole canned example would take a bit of effort as the images are fetched from the network etc.

**Comment by vinc3m1** [comment]
Do you have a copy of the image I could play with?

**Comment by alwaysthecritic** [comment]
Here's an example of one of the default Twitter avatars, where the egg is perfectly centred within the image: https://abs.twimg.com/sticky/default_profile_images/default_profile_2_normal.png

**Comment by aftabsikander** [comment]
Is there a workaround for this issue?

**Comment by alwaysthecritic** [comment]
For now I have my own versions of RoundedImageView and RoundedDrawable which I use in preference to the ones in the library, so that I can apply the fix (at least the fix that works for me, as detailed above).

The fixed code is in my RoundedDrawable, but you need RoundedImageView too, so that it uses the modified RoundedDrawable throughout.

**Comment by aftabsikander** [comment]
I have implemented your solution but the image is not centred when scale type is centre.
This happens only for some images.
Sample 1 image is not centred.
![sample_1](https://cloud.githubusercontent.com/assets/4800511/10016120/250dc054-613e-11e5-9509-1b21d209997c.PNG)

Sample 2 image is centred
![sample_2](https://cloud.githubusercontent.com/assets/4800511/10016122/2f0ec706-613e-11e5-894e-3c3e4dea0277.PNG)

Link to modified file 
https://gist.github.com/aftabsikander/2a9a994e9d721cb4a36d

**Comment by ivanviragine** [comment]
news on this?

**Comment by vinc3m1** [comment]
After taking a second look, looks like @alwaysthecritic had the right fix the whole time. Not sure why that didn't click the first time.
