### ISSUE TITLE
How to add a default text in case the image is not available?

### ISSUE THREAD

**Issue by 2hamed** [vinc3m1/RoundedImageView#82]
I'm trying to add something like [this](https://github.com/mauriciogior/Initials-ImageView) using your library but am trouble adding it.  
The said widget adds the text inside onDraw but your class does not override it. Can you help me on this?

**Comment by vinc3m1** [comment]
Why not just use that library then? My library overrides draw in the drawable, so you have to make sure that's drawn to the canvas. RoundedImageView is basically a proxy to RoundedDrawable.
