### ISSUE TITLE
Option to disable shader tiling if bitmap is smaller than ImageView

### ISSUE THREAD

**Issue by fpanizza** [vinc3m1/RoundedImageView#83]
I could reproduce this behavior with your example app. Just change the first image (photo1) in \res\drawable-nodpi\drawable-nodpi\ with the following image.
![photo1](https://cloud.githubusercontent.com/assets/338907/6562170/8a728bd2-c675-11e4-87d6-ba1404adce08.png)
It's just a small image.

At least in the first mode (CENTER) the image gets distorted.
See attached screenshot :
![2015-03-09 18 52 26](https://cloud.githubusercontent.com/assets/338907/6562185/a4a0be02-c675-11e4-9063-a14ccb047f9d.png)

Tks a lot,

**Comment by vinc3m1** [comment]
This is expected, and can be configured since we added support for [Shader.TileMode](http://developer.android.com/reference/android/graphics/Shader.TileMode.html).

**Comment by fpanizza** [comment]
ok, but none of the Shader.TileMode are appropriate for this case. 
Is there any way to show only the image (flag) in the center ?

**Comment by vinc3m1** [comment]
I can look into it

**Comment by squeeish** [comment]
Is this the same behaviour I'm experiencing here? You can see that the diamond is slightly off center.

![Imgur](http://i.imgur.com/cURr2Ra.png)

The code:

    <com.makeramen.roundedimageview.RoundedImageView
            android:id="@+id/themeIcon1"
            android:layout_width="50dp"
            android:layout_height="50dp"
            android:layout_centerHorizontal="true"
            android:scaleType="center"
            app:riv_corner_radius="30dip"
            app:riv_border_width="2dip"
            app:riv_border_color="#4C4C4C"
            app:riv_oval="true"
            />

            Picasso.with(getActivity())
                         .load(R.drawable.diamond)
		         .resize(80,80)
                         .into(themeIcon1);

**Comment by vinc3m1** [comment]
Haven't had time to look into this, open to ideas/PRs.
