### ISSUE TITLE
Related to new Picasso update

### ISSUE THREAD

**Issue by MoshDev** [vinc3m1/RoundedImageView#89]
please read this bug on Picasso since its related to your library, If you solves this problem from your side it would be great 

https://github.com/square/picasso/issues/943

**Comment by vinc3m1** [comment]
Please use [RoundedTransformationBuilder](https://github.com/vinc3m1/RoundedImageView#usage) if possible. This will depend on `TransitionDrawable` support which isn't ready yet.

Also it looks like they reverted their change already, but you should still try to use the transformation.
