### ISSUE TITLE
Support for different radii for each corner.

### ISSUE THREAD

**Issue by Vurtex** [vinc3m1/RoundedImageView#90]
I want an ImageView, it can even above the corner is round, below two Angle is rectangle, the control can be achieved?

**Comment by vinc3m1** [comment]
This is not supported at the moment, but there may be some options using paths to make this work. Won't be anytime soon though.

**Comment by Vurtex** [comment]
Thank you for answering。

**Comment by smer4ik** [comment]
Do you have some new information about this feature?
