### ISSUE TITLE
RoundedImageView gets clipped from all sides

### ISSUE THREAD

**Issue by osrl** [vinc3m1/RoundedImageView#91]
I'm not sure this is a bug or a mistake by me. mutateBackground is set to false. It gets clipped even without border. What is the reason of this?
Here is a screenshot. 
![image 2015-03-24 at 12 31 26 pm](https://cloud.githubusercontent.com/assets/781453/6804596/3ebee68a-d247-11e4-923a-a04823dc6d46.png)

**Comment by vinc3m1** [comment]
Do you have an original or expected output? Hard to tell without it. Also it looks like your image does have a border right now.

**Comment by osrl** [comment]
I've been looking for hours and I found the simple mistake after I've posted a new issue. Sorry it was my mistake, not a bug. I've set a negative padding somewhere in my code, so it gets clipped from all sides.
